### ISSUE TITLE
Failures sometimes indicated in green

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/notification-admin#1067]
Possibly consider if we could indicate all failures in red?
Perhaps we might also consider iconography here?  

<img width="495" alt="Screen Shot 2021-06-15 at 1 41 00 PM" src="https://user-images.githubusercontent.com/38330843/122098991-7d636880-cddf-11eb-9034-676669f8a9d9.png">

**Comment by yaelberger-commits** [comment]
Some failure don't affect our score, so it's acceptable rate of failure.
