### ISSUE TITLE
Remove hard-coded 'bank holiday's based on UK dates pattern, use database/external api.

### ISSUE THREAD

**Issue by obrien-j** [cds-snc/notification-admin#318]
https://github.com/cds-snc/notification-admin/blob/a6d55bfe6b52231bf97f75bce0364d37cb1903b3/app/main/views/feedback.py#L117

or at a minimum pull these dates out so they aren't hard coded. 

cc @pcraig3

**Comment by obrien-j** [comment]
Just changed issue description, could totally use Paul's holiday api. :)

**Comment by timarney** [comment]
The current contact form doesn't make use of this code anymore.  

It was used for tailoring the message for out of hours / holidays support.  That's not currently the case.
