### ISSUE TITLE
Silent Failure: Reply-to verification hangs in IE

### ISSUE THREAD

**Issue by ryanhyma** [cds-snc/notification-admin#368]
Using IE11 within TBS network, setting a reply-to hangs, waited about 10 minutes, verification email came... I did a hard refresh of the page and the proper confirmation showed. I'm guessing a JS problem.

**Comment by willeybryan** [comment]
After doing a deep dive and validation on this we can confirm that JS breaks site wide in IE. We cannot fix this without a complete re-do of the UI as Notify wasn't built with IE in mind. As Microsoft doesn't support IE anymore we don't see value in doing so. 

We must recommend users use MS Edge or Google Chrome.
