### ISSUE TITLE
Uploaded email branding images do not initially have public-read permission

### ISSUE THREAD

**Issue by smcmurtry** [cds-snc/notification-admin#395]
When new email branding is uploaded for a service, the preview image is broken:
<img width="581" alt="Screen Shot 2020-03-11 at 8 06 53 AM" src="https://user-images.githubusercontent.com/5498428/76442725-f7a87000-6386-11ea-99a5-c9c4e1253cee.png">

This is because the uploaded images are not publicly viewable, even though the S3 bucket they are uploaded to is. We could try setting public-read permission on the image when it is uploaded.

**Comment by maxneuvians** [comment]
💯 Just ensure we don't do a global update to S3 uploads because both CSV and document uploads need to remain private

**Comment by maxneuvians** [comment]
Fixed through S3 permissions fix
