### ISSUE TITLE
Missing translation in Conditions d’utilisation

### ISSUE THREAD

**Issue by lchski** [cds-snc/notification-admin#431]
[French Ts&Cs](https://notification.alpha.canada.ca/features/terms) contain this line:

> Follow Canadian law with regard to the privacy act when using this software.

Should be translated. Something like*...

> Respectez la loi canadienne (notamment la _Loi sur la protection des renseignements personnels_) lorsque vous utilisez ce logiciel.

Also, in English, "privacy act" should be title case and italicized: _Privacy Act_.

*I am not a translator, please have this checked.

**Comment by willeybryan** [comment]
Clementine has approved this message
