### ISSUE TITLE
OL Issues in 'flash' func calls

### ISSUE THREAD

**Issue by obrien-j** [cds-snc/notification-admin#495]
https://github.com/cds-snc/notification-admin/blob/4f1c55b28d8788a8c26a76ac6525c5d0e8fec121/app/main/views/verify.py#L60

Should likely grep for all of these flashes and see if there are other non-print functions that might push content as well, that missed translation.

**Comment by brdunfield** [comment]
Tracked in notification-api, and a big chunk of them got translated here: https://github.com/cds-snc/notification-api/pull/980
