### ISSUE TITLE
Package Bump

### ISSUE THREAD

**Issue by timarney** [cds-snc/notification-admin#74]
Per https://github.com/cds-snc/notification-admin/pull/56#issuecomment-514589905 we should be doing package bumps during our sprints.

**Todo:**

1. Bump Dependancies in Package.json

jQuery has a major version gap - we should use jquery-migrate to smooth the transition.
Bump jQuery from 1.x to 3.x
https://github.com/jquery/jquery-migrate#jquery-migrate

@willeybryan - we need to ensure we get a card in for every sprint to do security bumps.

> In doing so we'll figure out how much we trust the setup / tests

☝The sooner we figure that end out the better ☝

cc: @damcom333 @obrien-j

**Comment by willeybryan** [comment]
Yeah, we can do that.

**Comment by timarney** [comment]
Merged here:

https://github.com/cds-snc/notification-admin/pull/80#issuecomment-515149984

Todo:

> To bump jQuery to 3.x we need to investigate the failing tests for fullscreenTable.js

We can now accept PRs via Snyk or other tools easier :)
