### ISSUE TITLE
Adding a security key to Notify sends an email without "Updated information"

### ISSUE THREAD

**Issue by pcraig3** [cds-snc/notification-admin#761]
Hello!

I added a Yubikey to my profile on Notify and received this email about it:

![image](https://user-images.githubusercontent.com/2454380/93490471-81a53880-f8d6-11ea-98ef-be4bef6b54d7.png)

As you can see, it says `Updated information:` but then doesn't say what was updated. 

Not a high priority bug or anything, just thought I should let you know.

**Comment by willeybryan** [comment]
Crazy timing. I just made a bug ticket for this in our Product backlog https://trello.com/c/CiIbdIhk/24-adding-a-fido-2fa-key-generates-not-helpful-email

**Comment by AntoineAugusti** [comment]
🎉 
![Screen Shot 2020-09-17 at 11 27 07](https://user-images.githubusercontent.com/295709/93492396-c03bf280-f8d8-11ea-87ee-a4d15a46e3ef.png)

As you see, it's bugging us as well so we'll make sure to improve this

**Comment by AntoineAugusti** [comment]
Fixed in https://github.com/cds-snc/notification-api/pull/1128, will go to prod soon
